# Lechuza board configuration

# Copyright (c) 2022 elagil
# SPDX-License-Identifier: MIT

file_format: "1"
id: lechuza
name: Lechuza
type: board
arch: arm
features:
  - keys
outputs:
  - usb
url: https://github.com/elagil/lechuza
