# Polilla board configuration

# Copyright (c) 2020 elagil
# SPDX-License-Identifier: MIT

identifier: polilla
name: Polilla
type: mcu
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - usb_device
  - ble
  - ieee802154
  - pwm
  - watchdog
