on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
    - name: Display structure of artifacts
      run: ls -R
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          $GITHUB_WORKSPACE/*
